# main에 대한 pull_request가 closed될 때 workflow를 실행
on:
  pull_request:
    branches:
      - temp/CI-CD
    types:
      - closed
  workflow_dispatch: #수동 실행도 가능하도록
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true


# merge 내용이 반영된 새로운 container 생성 및 도커 허브에 push
jobs:
  release:
    runs-on: ubuntu-latest
    # pr의 결과가 merged인 경우만 jobs를 실행
    if: github.event.pull_request.merged == true

    steps:
    # ssh로 EC2 접속
    - name: Connect EC2 by SSH
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        first_ssh: |
          docker login -u ${{ secrets.DOCKER_HUB_EMAIL }} -p ${{ secrets.DOCKER_HUB_PW }} && docker pull hhzzo3ozz/familymoments:latest && docker run -p 7000:9000 --name familymoments
